### ISSUE TITLE
Make scikit-mine profile friendly

### ISSUE THREAD

**Issue by lgalarra** [scikit-mine/scikit-mine#104]
Hi,

Let us say that I want to profile some code that use scikit-mine. So far I have been using cProfile for this purpose. However, I realized that cProfile cannot report runtimes for function calls that run in other processes. If I take the following code as an example: 

```python
from skmine.datasets.fimi import fetch_chess
from skmine.itemsets import LCM

chess = fetch_chess()
chess.head()

lcm = LCM(min_supp=2000, n_jobs=4)
# minimum support of 2000, running on 4 processes
patterns = lcm.fit_discover(chess)

patterns[patterns.itemset.map(len) > 3]
```
and I run it

```
$ python3 -cProfile mycode.py
```
The function LCM._explore_root does not appear listed in the profiling report, presumably because it is wrapped by the function delayed, which is at the same time is wrapped by a Parallel object (line 182 in the lcm.py file).

#### Describe your proposed solution

The best solution I have come across is to add a flag in the LCM object (and similar miners) to force the code to run in the same process as the caller. I thought of something like this: 

```python
if self._exec_in_different_process :
    dfs = Parallel(n_jobs=self.n_jobs, prefer="processes")(
            delayed(self._explore_root)(item, tids) for item, tids in supp_sorted_items
        )
else : 
    for item, tids in supp_sorted_items :
        self._explore_root(item, tids)
```
I did this for HiPaR but I am not sure if it is best solution. I have not found ways to profile function calls in other processes that do not imply to touch scikit-mine's code.

**Comment by remiadon** [comment]
Hi @lgalarra, thanks for sharing !!

I use [snakeviz](https://jiffyclub.github.io/snakeviz/) (which uses cProfile under the hood)

When setting `n_jobs=1`, this is what I get 

![Screen Shot 2021-03-02 at 21 33 43](https://user-images.githubusercontent.com/2931080/109711403-21ae0000-7b9f-11eb-8f26-166da487568a.png)

when I launch
```python
from skmine.itemsets import LCM
%load_ext snakeviz
lcm = LCM(min_supp=2000, n_jobs=1)
# minimum support of 2000, single process for accurate profiling
%snakeviz -t patterns = lcm.fit_discover(chess)
```

**Comment by lgalarra** [comment]
Hi Rémi,

Thanks! snakeviz is pretty cool indeed! I do not see a reason to consider the proposed solution then!

Best,
Luis
