### ISSUE TITLE
Return type of SLIM

### ISSUE THREAD

**Issue by quaaasaaar** [scikit-mine/scikit-mine#124]
SLIM algorithm returns a pandas Series but all other algorithm from scikit-mine return a pandas DataFrame.

As pandas DataFrame are more friendly to use than pandas Series it could be interesting to switch the return type of SLIM to a pandas DataFrame. It will improve the consistency of scikit-mine.

**Comment by remiadon** [comment]
Hi @quaaasaaar , thanks for raising this issue :)

I guess returning a dataframe with two columns, namely `itemset` and `usage`, would fit your needs, am I right ?

NB: there are also concerns about using discovered patterns (here the `itemset` column) as an index, so one could "query" the resulting dataframe to obtain information that corresponds to a specific pattern

**Comment by quaaasaaar** [comment]
Such a dataframe would be perfect for my needs.

**Comment by remiadon** [comment]
@quaaasaaar would you be OK to raise a PR for this ?

**Comment by thomasbtnfr** [comment]
The discover method now returns a dataframe presented in the [documentation](https://scikit-mine.github.io/scikit-mine/reference/itemsets.html#skmine.itemsets.SLIM.discover).
