### ISSUE TITLE
preprocessing of transactionnal database affect code length

### ISSUE THREAD

**Issue by hermann74** [scikit-mine/scikit-mine#136]
**Describe the bug**
We don't have same result with a list of itemset (list of categorical item) and with one-hot encoded versions from :
  -  to_tabular : an unclear utils function that output DataFrame
  ```python
def to_tabular(D): return pd.Series(D).str.join('|').str.get_dummies(sep="|")
```

- OneHotDataframe : a custom MultiLabelBinarizer that output one-hot encoded Dataframe
```python
class OneHotDataframe(MultiLabelBinarizer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def transform(self, Z):
        return pd.DataFrame(super().transform(Z), columns=self.classes_)
```

**To Reproduce**
```python
    from skmine.itemsets import SLIM
    D = [['bananas', 'milk'], ['milk', 'bananas', 'cookies'], ['cookies', 'butter', 'tea']]
    new_D = [['cookies', 'butter']]  # to_tabular(
    slim = SLIM().fit(D)
    print("SCORE \n", slim.decision_function(new_D))
    print("CODE LENGTH\n", slim.get_code_length(new_D))
    
    onehot = OneHotDataframe()
    Done = onehot.fit_transform(D)
    new_Done = onehot.transform(new_D)
    print(pd.DataFrame(Done, columns=onehot.classes_))
    print(pd.DataFrame(new_Done, columns=onehot.classes_))
    #
    slim2 = SLIM().fit(Done)
    print("SCORE \n", slim2.decision_function(new_Done))
    print("CODE LENGTH\n", slim2.get_code_length(new_Done))
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. OS X]

**Additional context**

**Comment by thomasbtnfr** [comment]
The results of the first SLIM are good. We expect to obtain 5.58 with Laplace smoothing.

For the second case, it doesn't work because `Done` is an ndarray and new_Done is a `pd.Dataframe`. Both variables must be either an ndarray or a pd.Dataframe for the results to be identical to the first case.

**Comment by hermann74** [comment]
:+1:  Thanks ! Perhaps, documentation should point  that : same type for D in new_D when calling `slim.fit(D) ` and `slim.get_code_length(new_D)`.
Patch for  OneHotDataframe class :

```python
class OneHotDataframe(MultiLabelBinarizer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    def fit_transform(self, y):
        return pd.DataFrame(super().fit_transform(y), columns=self.classes_)
    def transform(self, Z):
        return pd.DataFrame(super().transform(Z), columns=self.classes_)
```
