### ISSUE TITLE
Bitmap implementation

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#2]
## Context
For many mining tasks, eg. tracking the transaction ids for every single items, we need efficient representations of **integers sets**. For this we will use [Roaring Bitmaps](http://www.roaringbitmap.org/publications/)

## Candidates
In python we have access to a few implementations, mainly
- [PyRoaringBitmap](https://github.com/Ezibenroc/PyRoaringBitMap) is a wrapper over CRoaring
- [https://github.com/andreasvc/roaringbitmap](https://github.com/andreasvc/roaringbitmap) is a pure Cython implementation 

To me the winner is [roaringbitmap](https://github.com/andreasvc/roaringbitmap), for:
  - it's written in pure cython, with cython bein a langage we want to investigate in, and widely use in this project, so this make a "unified" code base between our code and this external library
 - it is well implemented, well documented and well tested
- it includes a few more methods than other libraires, an example of this being the [intersection_len](https://roaringbitmap.readthedocs.io/en/latest/#roaringbitmap.RoaringBitmap.intersection_len) method

The only main issue I see is it's not conda installable yet, but we may work on it later.

**Comment by remiadon** [comment]
Closing this, no big opponents for now

**Comment by remiadon** [comment]
I already tried replacing `roaringbitmap==0.7` by `pyroaring==2.9.1` (another implementation), unittests are passing
I also re-ran the benchmarks, for SLIM there is no real difference, for LCM it drops by a factor of 1.2, which is acceptable

![image](https://user-images.githubusercontent.com/2931080/98445988-2d227a80-211b-11eb-97c4-681553494227.png)

![image](https://user-images.githubusercontent.com/2931080/98446013-4c210c80-211b-11eb-8b0b-2b7ad20dde5a.png)

**Comment by remiadon** [comment]
I aslo had a bug running https://github.com/scikit-mine/scikit-mine/pull/80/checks?sha=1818177e56e32daf7ce21480b3a98411f91ad2eb when installing dependencies on ubuntu-latest with python 3.x (which turned into 3.9)

I (quick)fixed it by setting `python-version: 3.7` in the CI

**Comment by remiadon** [comment]
https://github.com/scikit-mine/scikit-mine/pull/93 is using `pyroaring` because I got into big segfaults using `roaringbitmap`

Also note that `pyroaring` has a `next_set_bit` method, that appears to be very useful for sequential pattern mining, to answer questions like : "I am on position x, what is the next occurrence of event e from this position"

**Comment by thomasbtnfr** [comment]
Since v0.0.8, `pyroaring` is now used because `roaringbitmap` is not compatible with Python 3.11 at the moment.
