### ISSUE TITLE
better description of transactions

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#23]
#### Describe the issue linked to the documentation
As discussed wit @PeggyCellier  and @alexandre-termier 
FIMI datasets descriptions lack of extra informations on the nature of the data, and its potential use
In addition, some information about the **density** is missing
Finally, `describe_itemsets` seems not to be the best way to name the method in question
`describe_transactional_dataset` seems to be better, while my suggestion would be `describe_transactions`
@PeggyCellier what would you prefer ? I think `describe_transactions` is both short and explicit

#### Suggest a potential alternative/fix
- [x] add informations on usage in FIMI datasets docstrings
- [x] add a density field in fetch_* methods dosctrings
- [x] adapt description methods to yield information about density
- [x] choose a new name for `describe_itemsets` and modify the code

**Comment by remiadon** [comment]
@alexandre-termier @PeggyCellier  do you know where I can find usage infos on these datasets ?
The only info I have now is for retail and accidents

**Comment by PeggyCellier** [comment]
> @PeggyCellier what would you prefer ? I think describe_transactions is both short and explicit

I would prefer describe_dataset. Is it possible ?

**Comment by remiadon** [comment]
@PeggyCellier I have updated the name to "describe_transactions"

----------------------------
Rationale behind this

First, we have to stick with the **sklearn philosophy** as much as possible

scikit-learn provides a dedicated function for every single type of data generation,
for classification, they have a `make_classification` for classification, a `make_regression` for regression, etc ...
In our case we have classic "transactions", but in the future we may also add sequential transactions, and other types

In addition, we have to provide a consistent way to both generate data and check properties on this data  --> a ``make_transactions``, for which the mirror function is `describe_transactions`

`make_dataset` and `describe_dataset` would not make sense, at least in the sklearn framework.

I tried to find a **compromise**. Hope this syntax remains intuitive to you

**Comment by PeggyCellier** [comment]
I took a look on the last meeting and we decided to name it: skmine.datasets.utils.describe(D)
and to integrate the type of the data in the results of the function...
But the compatibility with sklearn is a good point...

@alexandre-termier what is your opinion?

**Comment by alexandre-termier** [comment]
I understand the need for compatibility with sklearn whenever possible. 
However, I do not agree with the make_X / describe_X argument.
When making a new dataset, of course precise information on the type of the dataset is required: the system has no way to infer it at that point. So I buy the "make_transaction" name.
But when describing a dataset, the dataset already exists and has a type: why would the user need to remember that for a transactional dataset she has to use function describe_transaction, and for

**Comment by remiadon** [comment]
@alexandre-termier  I get your point
I guess "describe" is the good way to go

If @PeggyCellier is OK with this name I'll change it

**Comment by PeggyCellier** [comment]
Yes it is ok for me :-)

**Comment by remiadon** [comment]
fixed in 7980faf1c1d61919ba796bbb23726dea23dc075e
