### ISSUE TITLE
LCM fit_transform as a form of One Hot Encoding

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#31]
I recently added a "fit_discover" method to LCM, wich renders patterns in a pretty format
This format is **made for pattern miners**

On the other, people from the Machine Learning community like to deal with **tabular formats**
This is currently addressed via ``fit_transform``
The current implementation just calls fit_discover, and then One-Hot-Encode (or dummify), the resulting patterns.

But this has several drawback 
 - different parameters will lead to different dimensions in the resulting matrix. As each pattern is a dimension, if you mine more pattern, you end up having more dimensions 
- this results in big memory consumption, because the matrix is big

**On chess** we have 3196 single items, but with a min_supp of 2000, we get more than 60K patterns.
With the current implementation **this leads to a DataFrame with more than 60K columns** ...

Proposed solution
People with ML background already know about `sklearn.preprocessing.OneHotEncoder`.
It may be a good solution to make LCM.fit_transform a sort of **more evolved OneHotEncoder**

How do we do this
Instead of setting every itemset as a column. We use items instead. This makes dimensions consistent between different runs. For every pattern, we fill the corresponding cells to the lengths of the pattern. 

Example
```python
   >>> from skmine.itemsets import LCM
   >>> D = [[1, 2, 3, 4, 5, 6], [2, 3, 5], [2, 5]]
    >>> lcm = LCM(min_supp=2)
    >>> lcm.fit_transform(D, sort=True)   # current solution
       (2, 5)  (2, 3, 5)
    0       1          1
    1       1          1
    2       1          0
    >>> lcm.fit_transform(D, sort=True)  # proposed solution
         2     3     5
    0    2     2     2
    1    2     2     2
    2    3     0     3
```

I am not sure about encoding pattern lengths in the result
But setting single items as columns is definitely a functional requirement

@PeggyCellier @alexandre-termier what do you think ?

**Comment by PeggyCellier** [comment]
I am not sure to well understand. 
In both solutions what are the rows? The number of transactions in the dataset? 
So "
   (2, 5)  (2, 3, 5)
    0       1          1
" means that pattern (2,5) and (2,3,5) appear in transaction 0?
whereas 
"
          2     3     5
    0    2     2     2
" means that item 2 appears in two patterns that appears in transaction 0?

**Comment by alexandre-termier** [comment]
I second the question of Peggy, I cannot understand the meaning of the cell values in the proposed solution. Especially, for transaction 0 as there are the same values for columns 2, 3 and 5 how can one know that we have only the itemsets (2,5) and (2,3,5) and nothing else? 

But on the principle, I agree that we cannot output a dataframe with 60k columns. And in many cases it will be way more than that!

**Comment by remiadon** [comment]
OK I guess that part was not clear

The rows are the transaction ids, starting from 0. This is why we have rows from 0 to 2 included, because the list passed as argument was of length 3

All we are trying to do is to **find a new representation of the original transactions, using the patterns we just discovered**

**Comment by remiadon** [comment]
EDIT there was a typo in the description

The example actually is

Example
```python
   >>> from skmine.itemsets import LCM
   >>> D = [[1, 2, 3, 4, 5, 6], [2, 3, 5], [2, 5]]
    >>> lcm = LCM(min_supp=2)
    >>> lcm.fit_transform(D, sort=True)   # current solution
       (2, 5)  (2, 3, 5)
    0       1          1
    1       1          1
    2       1          0
    >>> lcm.fit_transform(D, sort=True)  # proposed solution
         2     3     5   # columns are single items w.r.t to minimum support
    0    3     3     3   # (2, 3, 5) has length 3
    1    3     3     3   # (2, 3, 5) has length 3
    2    2     0     2   # (2, 5) has length 2
```

**Comment by remiadon** [comment]
Another solution would be encoding the support itself instead of the length of the pattern.
At the transaction level (row in the matrix) this is more informative

```python
   >>> from skmine.itemsets import LCM
   >>> D = [[1, 2, 3, 4, 5, 6], [2, 3, 5], [2, 5]]
    >>> lcm = LCM(min_supp=2)
    >>> lcm.fit_transform(D, sort=True)  # proposed solution
         2     3     5   # columns are single items w.r.t minimum support
    0    2     2     2   # (2, 3, 5) has length 3 but support of 2
    1    2     2     2   # (2, 3, 5) has length 3 but support of 2
    2    3     0     3   # (2, 5) has length 2 but support of 3
```

**Comment by remiadon** [comment]
see 829b53d7ad945189c838b1da44c22219966bc091
