### ISSUE TITLE
"interactions with sklearn" page in the doc

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#36]

**Comment by remiadon** [comment]
see https://github.com/scikit-mine/scikit-mine/commit/090f27fc78a859945708586786d19e3cc3de41d3

**Comment by alexandre-termier** [comment]
First version of this page is really nice, congrats!

For the Preprocessing section, we should have an example (through a link to a tutorial for example). Here, it says that sometimes we need to do things differently than sklearn, and that Preprocessing does the heavy lifting for the user, but this remains too abstract. 
Ideally, the reader should get some basic idea on the cases where it will require to use the Preprocessing elements of sk-mine.

**Comment by remiadon** [comment]
@alexandre-termier agreed 
Should we include a link to an example and in-line a self-explanatory example ?

**Comment by alexandre-termier** [comment]
If this is possible, this would be perfect!

**Comment by remiadon** [comment]
@alexandre-termier sorry I'll rephrase
Should we include a link to an example OR in-line a self-explanatory example ?

**Comment by alexandre-termier** [comment]
My bad, I did not understood.
Link to example should have priority.

**Comment by remiadon** [comment]
@alexandre-termier updated
https://scikit-mine.github.io/scikit-mine/sklearn_compat.html

**Comment by remiadon** [comment]
DONE, see 090f27fc78a859945708586786d19e3cc3de41d3 and 3111194a004d58364cc3ac3a9bf91a430962c16e
