### ISSUE TITLE
Skyline Queries

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#47]
#### Describe the workflow you want to enable
Skyline queries have been well studied and enable very usefull workflows.
For example if I want to find the optimal offers for a set of homes I would like to reserve for vacation, skyline queries allow me to keep (sort of cache) the set of homes that are on the skyline.

#### Describe your proposed solution
A ``SkylineClassifier`` class.
At `.fit` time, find the points on the skyline and keep them as an internal state.
This is possible because there are only a few points that verify the property of being on the skyline. A bit like MDL base methods, we get a concise representation.

A `decision_function` method would compute the distances from the skyline. If I pass new data to it, I should get a notion of "Is this product better than products from the skyline ?" 

#### Additional context
Max Halford wrote [a really nice post on it](https://maxhalford.github.io/blog/skyline-queries/)

**Comment by alexandre-termier** [comment]
As of now, Skyline Queries are not in the scikit-mine scope, I think they are a bit too far from our primary interest. 

We may at some point be interested in extensions of skyline queries such as skypatterns :

Arnaud Soulet, Chedy Raïssi, Marc Plantevit, Bruno Crémilleux: _Mining Dominant Patterns in the Sky_. ICDM 2011: 655-664  -> https://ieeexplore.ieee.org/document/6137270

They allow to find patterns that are good tradeoffs over several measures, which is interesting. 

One problem is that even if skyline/skypatterns are some form of condensed representation, there is no guarantee that there is not a huge number of skylines/skypatterns -> this is not a "pattern set" approach per se. 
I would prefer that for scikit-mine we stick as much as possible to "pattern set" approaches, based on MDL for now.
